# TODO: fundamental respetar el orden de los includes
#-include modulo.cfg
# TODO: fundamental respetar el orden de los includes
-include static.cfg
-include ../../project.cfg
-include ../Makefile

# .DEFAULT_GOAL:=compile_static

# compile_static: $(DIR_BIN)/$(STATIC_BIN)

# # TODO: refactor
# $(DIR_BIN)/$(STATIC_BIN): $(OBJ)
# 	$(COMPILE)
# 	@echo $(LOG) $(COMPILE_DESCRIPTION) $(MSG_OK)

# .PHONY: compile_static
