int conectarse_a_cpu(char * conexion_puerto);
int es_esta_instruccion(char * identificador,char ** params);
int main();
int pcb_get_posicion(t_pcb * pcb,t_list * lista);
t_pcb * minimum_estimacion_rafaga(t_pcb * pcb1,t_pcb * pcb2);
t_pcb * select_pcb_by_fifo(t_cola_planificacion * cola);
t_pcb * select_pcb_by_srt(t_cola_planificacion * cola);
void * iniciar_corto_plazo();
void * iniciar_largo_plazo();
void * iniciar_mediano_plazo();
void agregar_pcb_a_cola(t_pcb * pcb,t_cola_planificacion * cola);
void cambiar_estado_pcb(t_pcb * pcb,t_pcb_estado nuevoEstado);
void enviar_interrupcion();
void inicializar_cola(t_cola_planificacion * cola);
void iniciar_planificacion();
void remover_pcb_de_cola(t_pcb * pcb,t_cola_planificacion * cola);
void transicion_blocked_a_ready(t_pcb * pcb);
void transicion_susblocked_a_susready(t_pcb * pcb);
