-include ../../tests.cfg

# TODO: lo movimos a tests.cfg, temporalmente se deja comentado por si falla

#INCLUDE+=-I/home/jelou/Documents/git/manu-cproject/project/modulo-2/include
#OBJS_REQUIRED_BY_TESTS=/home/jelou/Documents/git/manu-cproject/project/modulo-2/.obj/sample.o

#INCLUDE+=-I../include
#OBJS_REQUIRED_BY_TESTS=$(wildcard ../.obj/*.o)
