DATETIME_FORMAT != date +%T
# alternativa: date +%F-%H:%M

LOG_DATETIME="\033[32m[$(DATETIME_FORMAT)]\033[0m"
LOG_MODULE_NAME="\033[33m[$(CURRENT_MODULE_NAME)]\033[0m"
LOG = $(LOG_DATETIME) $(LOG_MODULE_NAME)
