-include ../Makefile.cfg

# agregamos la nueva biblioteca a las macros ya predefinidas

# le avisamos al pre-procesador de C donde encontrar los archivos de cabecera .h
CPPFLAGS +=-I$(DIR_LIB_CSPEC)

# gcc le indica al GNU linker la ruta donde buscar bibliotecas
LDFLAGS += -L/usr/include -L$(DIR_LIB_CSPEC_BIN)

# gcc le indica al GNU linker que bibliotecas usar (agregar luego de los source files)
LDLIBS += -lpthread -lcspecs
